import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import software.ulpgc.aoc.day07.GridBuilder;
import software.ulpgc.aoc.day07.LabController;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class Day07BTest {

    private final String EXAMPLE_INPUT = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """;

    @Test
    public void testTemporalLinesExample() {
        GridBuilder builder = new GridBuilder();
        EXAMPLE_INPUT.lines().forEach(builder::addLine);
        LabController controller = new LabController(builder.build());
        long result = controller.countTemporalLines();
        assertEquals(40L, result, "The total number of timelines should be 40");
    }
}