import org.junit.jupiter.api.Test;
import software.ulpgc.aoc.day07.GridBuilder;
import software.ulpgc.aoc.day07.LabController;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class Day07ATest {

    private final String EXAMPLE_INPUT = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """;

    @Test
    public void testDivisionsExample() {
        GridBuilder builder = new GridBuilder();
        EXAMPLE_INPUT.lines().forEach(builder::addLine);
        LabController controller = new LabController(builder.build());
        int result = controller.countDivisions();
        assertEquals(21, result, "The number of divisions should be 21");
    }
}