import org.junit.jupiter.api.Test;
import software.ulpgc.aoc.day07.control.GridBuilder;
import software.ulpgc.aoc.day07.control.LabController;
import software.ulpgc.aoc.day07.model.LabProtocol;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class Day07ATest {

    private final String EXAMPLE_INPUT = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """;

    @Test
    public void testDivisionsExample() {
        LabProtocol countDivisions = solved -> solved.accumulatedDivisions();
        LabController controller = new GridBuilder()
                .from(EXAMPLE_INPUT.lines().toList())
                .using(countDivisions)
                .build();
        long result = controller.run();
        assertEquals(21L, result, "The number of divisions should be 21");
    }
}
