import org.junit.jupiter.api.Test;
import software.ulpgc.aoc.dia07.ConstructorRejilla;
import software.ulpgc.aoc.dia07.ControladorLaboratorio;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class Dia07ATest {

    private final String INPUT_EJEMPLO = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """;

    @Test
    public void testDivisionesEjemplo() {
        ConstructorRejilla builder = new ConstructorRejilla();
        INPUT_EJEMPLO.lines().forEach(builder::agregarLinea);
        ControladorLaboratorio controlador = new ControladorLaboratorio(builder.construir());
        int resultado = controlador.contarDivisiones();
        assertEquals(21, resultado, "El número de divisiones debería ser 21");
    }
}