import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import software.ulpgc.aoc.dia07.ConstructorRejilla;
import software.ulpgc.aoc.dia07.ControladorLaboratorio;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class Dia07BTest {

    private final String INPUT_EJEMPLO = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """;

    @Test
    public void testLineasTemporalesEjemplo() {
        ConstructorRejilla builder = new ConstructorRejilla();
        INPUT_EJEMPLO.lines().forEach(builder::agregarLinea);
        ControladorLaboratorio controlador = new ControladorLaboratorio(builder.construir());
        long resultado = controlador.contarLineasTemporales();
        assertEquals(40L, resultado, "El total de líneas temporales debería ser 40");
    }
}